version: "3.8"

services:
  backend:
    build: ./Backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./Frontend
      args:
        NEXT_PUBLIC_API_URL: http://20.151.170.182:8000
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://20.151.170.182:8000
    depends_on:
      - backend