version: "3.8"

services:
  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build:
      context: ./Frontend
      args:
        NEXT_PUBLIC_API_URL: http://40.76.254.32:8000
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://40.76.254.32:8000
    depends_on:
      - backend
